### ISSUE TITLE
Provide `--help` for subcommands

### ISSUE THREAD

**Issue by r8d8** [ETCDEVTeam/emerald-cli#91] opened 2018-03-21 07:15 UTC
Currenlty `emerald-cli` provides only top level help, due to limitations of `docopt` crate.
Ex.: `emerald --help`

Required detailed help for each command, like [rustup](https://github.com/rust-lang-nursery/rustup.rs) have.
Ex.: `emerald list --help`

**Comment by whilei** [comment] 2018-03-21 14:17
looks like duplicate of #47

**Closed** 2018-03-21 14:23 UTC
Labels: enhancement
